### ISSUE TITLE
Installation Error (Ubuntu 14.04 - Remote machine with No Root Access)

### ISSUE THREAD

**Issue by Viswa14** [HyeonwooNoh/caffe#7]
## When I try to set up modified Caffe Version to execute DeConvnet, I get errors in Make all as:

CXX/LD -o .build_release/test/test_all.testbin src/caffe/test/test_caffe_main.cpp
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libopencv_highgui.so: undefined reference to `TIFFReadRGBAStrip@LIBTIFF_4.0'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libopencv_highgui.so: undefined reference to`TIFFIsTiled@LIBTIFF_4.0'
//usr/lib/x86_64-linux-gnu/libunwind.so.8: undefined reference to `lzma_stream_buffer_decode@XZ_5.0'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libopencv_highgui.so: undefined reference to`TIFFWriteScanline@LIBTIFF_4.0'

---

I Would like to know which version of OpenCV is needed for this modified Caffe also Is it mandatory to install Opencv to get this running ? Kindly Help !! Thank you.

**Comment by williford** [comment]
OpenCV is required for the segmentation code to work. I've gotten it to work with version 2.4.9.
